# Generated by Django 2.2.3 on 2020-03-07 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('name_owner', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('planes', models.ImageField(blank=True, null=True, upload_to='')),
                ('fuerzas_horizontales', models.CharField(max_length=200)),
                ('fuerzas_verticales', models.IntegerField(blank=True, null=True)),
                ('value_type_construccion', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('type_construccion', models.CharField(max_length=200)),
                ('type_property', models.IntegerField(blank=True, null=True)),
                ('irregular_long', models.CharField(max_length=200)),
                ('irregular_plant', models.CharField(max_length=200)),
                ('val_irregular_long', models.IntegerField(blank=True, null=True)),
                ('val_irregular_plant', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('height_floors', models.IntegerField(blank=True, null=True)),
                ('Width_x_placa', models.IntegerField(blank=True, null=True)),
                ('Width_y_placa', models.IntegerField(blank=True, null=True)),
                ('thickness_placa', models.IntegerField(blank=True, null=True)),
                ('ancho_viga', models.IntegerField(blank=True, null=True)),
                ('alto_viga', models.IntegerField(blank=True, null=True)),
                ('largo_viga', models.IntegerField(blank=True, null=True)),
                ('numero_viga', models.IntegerField(blank=True, null=True)),
                ('ancho_columna', models.IntegerField(blank=True, null=True)),
                ('alto_columna', models.IntegerField(blank=True, null=True)),
                ('largo_columna', models.IntegerField(blank=True, null=True)),
                ('numero_columna', models.IntegerField(blank=True, null=True)),
                ('cordenada_x', models.IntegerField(blank=True, null=True)),
                ('cordenada_y', models.IntegerField(blank=True, null=True)),
                ('type_suelo', models.CharField(max_length=200)),
                ('fa', models.IntegerField(blank=True, null=True)),
                ('fv', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
