# Generated by Django 2.2.3 on 2020-05-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('result_pdf', models.TextField()),
                ('process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Process')),
            ],
        ),
    ]
