# Generated by Django 3.0.6 on 2020-05-07 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['name'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name'], 'verbose_name': 'Carpeta', 'verbose_name_plural': 'Carpetas'},
        ),
        migrations.AlterModelOptions(
            name='logdoc',
            options={'ordering': ['-date'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historiales'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='coments',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='logdoc',
            name='parent',
        ),
        migrations.AddField(
            model_name='logdoc',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='es una documento privado'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.File', verbose_name='carpeta a la que pertenece el documento'),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='es una carpeta privada'),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.File', verbose_name='carpeta padre'),
        ),
        migrations.AlterField(
            model_name='logdoc',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de la acción'),
        ),
    ]
