# Generated by Django 3.0.6 on 2020-05-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['id'], 'verbose_name': 'Carpeta', 'verbose_name_plural': 'Carpetas'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='is_private',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='is_private',
            new_name='is_public',
        ),
    ]
