# Generated by Django 3.0.6 on 2020-05-07 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200507_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='action',
        ),
        migrations.AlterField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='documento publico'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Folder', verbose_name='ruta del documento'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='carpeta publica'),
        ),
        migrations.AlterField(
            model_name='history',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Document'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
