# Generated by Django 3.0.6 on 2020-05-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200508_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalHistory',
            new_name='HistoricalHistory2',
        ),
        migrations.RenameModel(
            old_name='History',
            new_name='History2',
        ),
    ]
