# Generated by Django 3.0.6 on 2020-05-08 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200508_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHistory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('user', models.CharField(max_length=250, verbose_name='usuario')),
                ('document', models.CharField(max_length=250, verbose_name='documento')),
                ('name_documento', models.CharField(max_length=250, verbose_name='nombre documento')),
                ('serie', models.CharField(max_length=250, verbose_name='serie')),
                ('date', models.DateTimeField(blank=True, editable=False, verbose_name='fecha de la acción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Historial',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, verbose_name='usuario')),
                ('document', models.CharField(max_length=250, verbose_name='documento')),
                ('name_documento', models.CharField(max_length=250, verbose_name='nombre documento')),
                ('serie', models.CharField(max_length=250, verbose_name='serie')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de la acción')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalhistory2',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='History2',
        ),
        migrations.DeleteModel(
            name='HistoricalHistory2',
        ),
    ]
