# Generated by Django 3.0.6 on 2020-05-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200507_0509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Folder',
        ),
    ]
