# Generated by Django 3.0.6 on 2020-05-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200508_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalhistory',
            old_name='name_document',
            new_name='name_documento',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='name_document',
            new_name='name_documento',
        ),
    ]
