# Generated by Django 3.0.6 on 2020-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200511_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='location',
            field=models.CharField(default='a', max_length=200, verbose_name='ubicacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='location',
            field=models.CharField(default='a', max_length=200, verbose_name='ubicacion'),
            preserve_default=False,
        ),
    ]
