# Generated by Django 3.0.6 on 2020-05-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200511_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ubicacion'),
        ),
        migrations.AlterField(
            model_name='historicalfolder',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ubicacion'),
        ),
    ]
