# Generated by Django 3.0.6 on 2020-05-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200511_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='location',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='historicalfolder',
            old_name='location',
            new_name='url',
        ),
    ]
