# Generated by Django 3.0.6 on 2020-05-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200511_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='url',
            new_name='url_folder',
        ),
        migrations.RenameField(
            model_name='historicalfolder',
            old_name='url',
            new_name='url_folder',
        ),
    ]
