# Generated by Django 3.0.6 on 2020-05-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200511_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='url_folder',
        ),
        migrations.RemoveField(
            model_name='historicalfolder',
            name='url_folder',
        ),
    ]
