# Generated by Django 3.0.6 on 2020-05-12 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200512_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Folder', verbose_name='ubicación'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Folder', verbose_name='ubicación'),
        ),
    ]
