# Generated by Django 3.0.6 on 2020-05-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200512_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='name2',
            field=models.CharField(default='rr.', max_length=200, verbose_name='nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='name2',
            field=models.CharField(default='s', max_length=200, verbose_name='nombre'),
            preserve_default=False,
        ),
    ]
