# Generated by Django 3.0.6 on 2020-05-13 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200513_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='historicalfolder',
            name='name2',
        ),
    ]
