# Generated by Django 3.0.6 on 2020-05-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200513_0005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalFolder',
        ),
    ]
